# Generated by Django 4.0.3 on 2022-04-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='publish',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
