# Generated by Django 4.0.3 on 2022-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_events_publish_alter_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='cos',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
