# Generated by Django 4.0.3 on 2022-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_events_cos_alter_events_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='cos',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
