# Generated by Django 4.0.3 on 2022-04-01 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_events_cos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='cos',
        ),
        migrations.AddField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='gallery.events'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.BigAutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
