# Generated by Django 4.0.3 on 2022-04-02 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_events_cos_gallery_event_alter_events_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
