# Generated by Django 4.0.3 on 2022-04-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_events_publish_alter_events_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date_of_event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
