# Generated by Django 4.0.3 on 2022-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='information',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
