# Generated by Django 4.0.3 on 2022-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_child_alter_main_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='phone_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='phone_2',
            field=models.IntegerField(null=True),
        ),
    ]
