# Generated by Django 4.0.3 on 2022-04-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_child_phone_1_remove_child_phone_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_full_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
