# Generated by Django 4.0.3 on 2022-04-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_child_email_alter_child_father_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='information',
            field=models.TextField(),
        ),
    ]
