# Generated by Django 4.0.3 on 2022-04-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_child_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='information',
            field=models.TextField(null=True),
        ),
    ]
