# Generated by Django 4.0.3 on 2022-04-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_child_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(upload_to='users/%Y/%m/%d'),
        ),
    ]
