# Generated by Django 4.0.3 on 2022-04-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_child_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='email',
        ),
    ]
