# Generated by Django 4.0.3 on 2022-04-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_child_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
