# Generated by Django 4.0.3 on 2022-04-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_child_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='name',
            new_name='first_name',
        ),
    ]
