# Generated by Django 4.0.3 on 2022-04-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_child_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
