# Generated by Django 4.0.3 on 2022-04-06 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0034_alter_child_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='id_name',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
