# Generated by Django 4.0.3 on 2022-04-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_child_date_of_birth_alter_child_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='child',
            name='father_full_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_full_name',
            field=models.CharField(max_length=40),
        ),
    ]
