# Generated by Django 4.0.3 on 2022-04-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_child_father_full_name_alter_child_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='father_full_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='child',
            name='mother_full_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
