# Generated by Django 4.0.3 on 2022-04-08 18:59

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_child_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(upload_to=blog.models.upload_gallery_image),
        ),
    ]
