# Generated by Django 4.0.3 on 2022-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0043_alter_child_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
