# Generated by Django 4.0.3 on 2022-04-08 20:13

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_alter_post_comments'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_gallery_image),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
